### ISSUE TITLE
This package has build errors. 

### ISSUE THREAD

**Issue by CiaranWelsh** [sys-bio/libroadrunner-deps#9]
I've just tried building this package on both Ubuntu18.04 and Windows with msvc 2019 compilers and Jin has tried on a Mac. All systems have failed by the looks of things. 

## The Ubuntu error
Running: 
```
mkdir build && cd build
cmake ..
make
```
Causes my terminal to hang whilst looking for sbml-dependencies: 
```
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/d/RoadRunner/libroadrunner-deps/build
make[1]: Warning: File 'CMakeFiles/Makefile2' has modification time 0.4 s in the future
Scanning dependencies of target sbml-static
```

I opened up the project in CLion and built each target independently. They all work except for `libsbml` and `poco` foundations, both of which hang. 

## The MSVC error: 
```
Building static libraries
Building without tests & samples
Build with using internal copy of sqlite, libz, pcre, expat, ...
Found OpenSSL: C:/Miniconda/Library/lib/libcrypto.lib (found version "1.1.1d")  
Couldn't find MySQL
XXX: MS Visual Compiler detected
CMake Error at third_party/poco_1.5.3/Foundation/CMakeLists.txt:18 (message):
  message compiler not found: required to build


Configuring incomplete, errors occurred!
See also "D:/RoadRunner/libroadrunner-deps/build-msvc/CMakeFiles/CMakeOutput.log".
See also "D:/RoadRunner/libroadrunner-deps/build-msvc/CMakeFiles/CMakeError.log".
```
I havent dug into this more. 

# The Mac error: 
```
... waiting for unfinished jobs
```
Note, I do not have a Mac so can't paste the actual error. 

Workaround for now: Install `POCO` and `libsbml` manually. Install them to system wide location so they are easily findable, i.e. `program files` for windows or `/usr/*` for linux. Not sure what this is on the mac. I'd also try to keep the versions of each of these the same as what was originally used to build this package as well.

**Comment by kirichoi** [comment]
The MSVC error is related the cmake not being able to pick up `mc.exe` automatically. I always had to manually specify the path.

**Comment by CiaranWelsh** [comment]
Thanks Kiri, looks like I was a bit short sighted with the MSVC error - I should have put more into troubleshooting. 

I was able to fully compile this package under MSVC 2019 compilers using CLion as front end.
